language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
install: true
services:
- docker
script: ./mvnw clean install docker:build docker:push -Ddocker.username=$docker_username -Ddocker.password=$docker_password