kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: tube
  name: service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
